//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcialDos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public int_clientes()
        {
            this.Recepcion = new HashSet<Recepcion>();
        }
    
        public int Rut { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Giro { get; set; }
        public Nullable<int> Fonos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recepcion> Recepcion { get; set; }
    }
}
