//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcialDos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recepcion
    {
        public int Id { get; set; }
        public Nullable<int> CliRut { get; set; }
        public Nullable<int> LabId { get; set; }
        public int Folio { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string Localidad { get; set; }
        public Nullable<int> CantidadMuestras { get; set; }
    
        public virtual int_clientes int_clientes { get; set; }
        public virtual Laboratorios Laboratorios { get; set; }
    }
}
